package com.rules;

import com.ashokit.model.Product

rule "Silver Offer"
 	when 
 		productObject: Product(productType=="silver")
 	then 
 		productObject.setDiscount(5.0);
 	end 	

rule "Gold Offer"
	when 
 		productObject: Product(productType=="gold")
 	then 
 		productObject.setDiscount(10.0);
 	end 

rule "Diamond Offer"
	when 
 		productObject: Product(productType=="diamond")
 	then 
 		productObject.setDiscount(15.0);
 	end 